name: template

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      NODE_ENV: development  
    init: true
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: ./src
        target: /app/container-app
    working_dir: /app/container-app
    tty: true
    # command: bash -c "cd /app/container-app && npm run dev"
